name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: ^15.x
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go
      - name: Install staticcheck
        run: go install github.com/lightclient/rpctestgen/cmd/speccheck@latest
      - name: Run staticcheck
        run: test -d tests && speccheck -v

